server:
  port: 4004

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Corrected: 'path' is now 'Path'
            - id: patient-service-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1 # Note: Also good practice to capitalize Filter names

            # Corrected: 'path' is now 'Path'
            - id: api-docs-patient-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api-docs/patients
              filters:
                - RewritePath=/api-docs/patients, /v3/api-docs