### Post request to create patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe Kafka test",
  "email": "testing_kafka@email.com",
  "address": "123 main street",
  "dateOfBirth": "1995-02-12",
  "registeredDate": "2025-10-17"
}

###